source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('accounts/login', LoginView.as_view(template_name="login.html"), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout')
]

source/articles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

source/webapp/urls.py
from django.urls import path
from webapp.views.articles import ArticleListView,ArticleCreateView,ArticleView, ArticleUpdateView,ArticleDeleteView
from webapp.views.comments import CommentsCreateView, CommentUpdateView, CommentDeleteView

app_name = 'webapp'
urlpatterns = [
    path('', ArticleListView.as_view(), name="articles"),
    path('article/add/', ArticleCreateView.as_view(), name="create_article"),
    path('article/<int:pk>/', ArticleView.as_view(), name="article_detail"),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name="update_article"),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name="delete_article"),
    path('article/<int:pk>/comment/add/', CommentsCreateView.as_view(), name="comment_add"),
    path('comment/<int:pk>/update', CommentUpdateView.as_view(), name="update_comment"),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name="delete_comment"),
]

source/webapp/models/article.py
from django.db import models
from webapp.models import BaseModel
from django.urls import reverse

class Article(BaseModel):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name="Заголовок")
    author = models.CharField(max_length=50, null=False, blank=False, verbose_name="Автор")
    content = models.TextField(null=False, blank=False, verbose_name="Контент")
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True)



    def __str__(self):
        return f'{self.id}. {self.title}'

    class Meta:
        db_table = 'articles'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.pk})

source/webapp/models/base.py
from django.db import models



class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    class Meta:
        abstract = True

source/webapp/models/comment.py
from django.db import models
from webapp.models import BaseModel


class Comment(BaseModel):
    article = models.ForeignKey('webapp.Article', related_name='comments', on_delete=models.CASCADE,
                                verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.CharField(max_length=40, null=True, blank=True, default='Аноним', verbose_name='Автор')

    def __str__(self):
        return self.text[:20]

    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

source/webapp/models/tag.py
from django.db import models
from webapp.models import BaseModel


class Tag(BaseModel):
    name = models.CharField(max_length=31, verbose_name='Тег', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tags'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

source/webapp/forms/articles.py
from django import forms
from django.forms import widgets
from webapp.models import Tag, Article
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator

def at_least_5(string):
    if len(string) < 5:
        raise ValidationError('Поле не может быть короче 5 символов')


class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=50, required=True, validators=(at_least_5,), label="Название" )
    class Meta:
        model = Article
        fields = ('title', 'author', 'content', 'tags')
        widgets = {
            'tags': widgets.CheckboxSelectMultiple()
        }

#class ArticleForm(forms.Form):
#    title = forms.CharField(max_length=50, required=True, #validators=(at_least_5,),
#                            validators=(MinLengthValidator(5),),
#                            label="Название")
#    content = forms.CharField( required=True, label="Текст", widget=widgets.Textarea)
#    author = forms.CharField(max_length=50, required=True, label="Автор")
#    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), label="Теги", required=True)


    #def clean_title(self):
    #    title = self.clean_data["title"]
    #    if len(title)<5:
    #        raise ValidationError('Поле не может быть короче 5 символов')

    def clean(self):
         title = self.cleaned_data.get('title')
         content = self.cleaned_data.get('content')
         if title and content and title == content:
             raise ValidationError('Заголовок и контент не могут быть равны')

         return super().clean()

source/webapp/forms/comments.py
from django import forms
from django.forms import widgets
from webapp.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'author')

source/webapp/forms/search.py
from django import forms


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

source/webapp/views/articles.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.utils.http import urlencode
from django.contrib.auth.mixins import LoginRequiredMixin
from webapp.forms import ArticleForm, SimpleSearchForm
from webapp.models import Article
from django.views.generic import View, TemplateView, FormView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q


# Create your views here.


class ArticleListView(ListView):  # View

    model = Article
    template_name = 'articles/index.html'
    context_object_name = "articles"
    ordering = ["-created_at"]
    is_paginated = True
    paginate_by = 3
    paginate_orphans = 1

    def dispatch(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) | Q(author__icontains=self.search_value))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # super(ArticleListView, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
            context["search_value"] = self.search_value
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'articles/article_create.html'
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={"pk": self.object.pk})

    #def dispatch(self, request, *args, **kwargs):
    #    if request.user.is_authenticated:
    #        return super().dispatch(request, *args, **kwargs)
    #    else:
    #       return redirect("accounts:login")

    #def form_valid(self, form):
    #    article = form.save()
    #    return redirect("webapp:article_detail", pk=article.pk)  # super().form_valid(form)


class ArticleView(DetailView):
    template_name = 'articles/article_view.html'
    model = Article
    context_object_name = "article"

    def get_context_object_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = self.object.comments.order_by("created_at")  # self.get_object()
        return context


class ArticleUpdateView(UpdateView):
    model = Article
    template_name = "articles/article_update.html"
    form_class = ArticleForm


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = "articles/delete_article.html"
    success_url = reverse_lazy("webapp:articles")

source/webapp/views/comments.py
from django.views.generic import CreateView, UpdateView, DeleteView
from webapp.models import Comment, Article
from webapp.forms import CommentForm
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect


class CommentsCreateView(CreateView):
    model = Comment
    template_name = "comments/comment_create.html"
    form_class = CommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        form.instance.article = article
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={"pk": self.object.article.pk})


class CommentUpdateView(UpdateView):
    model = Comment
    template_name = "comments/comment_update.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={"pk": self.object.article.pk})

class CommentDeleteView(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect("webapp:article_detail", pk=self.object.article.pk)

source/webapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Articles{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'webapp:articles' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'webapp:articles' %}">Articles</a>
                </li>

                {% block menu %}{% endblock %}

                {% if not request.user.is_authenticated %}

                    <a class="nav-link ms-auto" aria-current="page" href="{% url 'accounts:login' %}">IN IN IN!</a>

                {% else %}
                {% endif %}
                {% if request.user.is_authenticated %}

                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <input class="nav-link" type="submit" value="выхiд">
                    </form>

                {% else %}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>




<div class="container">
    {% block content %}

    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/form.html
{% extends "base.html" %}

{% block content %}
    
<div class="container mt-5">

<h1>Новая запись</h1>
    <form action="{% url 'create' %}" method="post">
    {% include "partial/article_form.html" with button="Сохранить" %}
</form>

</div>


{% endblock %}