source/articles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

source/webapp/urls.py
from django.urls import path
from webapp.views.articles import ArticleListView,ArticleCreateView,ArticleView, ArticleUpdateView,ArticleDeleteView
from webapp.views.comments import CommentsCreateView, CommentUpdateView, CommentDeleteView

app_name = 'webapp'
urlpatterns = [
    path('', ArticleListView.as_view(), name="articles"),
    path('article/add/', ArticleCreateView.as_view(), name="create_article"),
    path('article/<int:pk>/', ArticleView.as_view(), name="article_detail"),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name="update_article"),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name="delete_article"),
    path('article/<int:pk>/comment/add/', CommentsCreateView.as_view(), name="comment_add"),
    path('comment/<int:pk>/update', CommentUpdateView.as_view(), name="update_comment"),
    path('comment/<int:pk>/delete', CommentDeleteView.as_view(), name="delete_comment"),
]

source/webapp/models/article.py
from django.db import models
from webapp.models import BaseModel
from django.urls import reverse

class Article(BaseModel):
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name="Заголовок")
    author = models.CharField(max_length=50, null=False, blank=False, verbose_name="Автор")
    content = models.TextField(null=False, blank=False, verbose_name="Контент")
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True)



    def __str__(self):
        return f'{self.id}. {self.title}'

    class Meta:
        db_table = 'articles'
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.pk})

source/webapp/models/base.py
from django.db import models



class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    class Meta:
        abstract = True

source/webapp/models/comment.py
from django.db import models
from webapp.models import BaseModel


class Comment(BaseModel):
    article = models.ForeignKey('webapp.Article', related_name='comments', on_delete=models.CASCADE,
                                verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.CharField(max_length=40, null=True, blank=True, default='Аноним', verbose_name='Автор')

    def __str__(self):
        return self.text[:20]

    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

source/webapp/models/tag.py
from django.db import models
from webapp.models import BaseModel


class Tag(BaseModel):
    name = models.CharField(max_length=31, verbose_name='Тег', unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tags'
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

source/webapp/forms/articles.py
from django import forms
from django.forms import widgets
from webapp.models import Tag, Article
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator

def at_least_5(string):
    if len(string) < 5:
        raise ValidationError('Поле не может быть короче 5 символов')


class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=50, required=True, validators=(at_least_5,), label="Название" )
    class Meta:
        model = Article
        fields = ('title', 'author', 'content', 'tags')
        widgets = {
            'tags': widgets.CheckboxSelectMultiple()
        }

#class ArticleForm(forms.Form):
#    title = forms.CharField(max_length=50, required=True, #validators=(at_least_5,),
#                            validators=(MinLengthValidator(5),),
#                            label="Название")
#    content = forms.CharField( required=True, label="Текст", widget=widgets.Textarea)
#    author = forms.CharField(max_length=50, required=True, label="Автор")
#    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), label="Теги", required=True)


    #def clean_title(self):
    #    title = self.clean_data["title"]
    #    if len(title)<5:
    #        raise ValidationError('Поле не может быть короче 5 символов')

    def clean(self):
         title = self.cleaned_data.get('title')
         content = self.cleaned_data.get('content')
         if title and content and title == content:
             raise ValidationError('Заголовок и контент не могут быть равны')

         return super().clean()

source/webapp/forms/comments.py
from django import forms
from django.forms import widgets
from webapp.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'author')

source/webapp/forms/search.py
from django import forms


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")

source/webapp/views/articles.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.utils.http import urlencode
from django.contrib.auth.mixins import LoginRequiredMixin
from webapp.forms import ArticleForm, SimpleSearchForm
from webapp.models import Article
from django.views.generic import View, TemplateView, FormView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q


# Create your views here.


class ArticleListView(ListView):  # View

    model = Article
    template_name = 'articles/index.html'
    context_object_name = "articles"
    ordering = ["-created_at"]
    is_paginated = True
    paginate_by = 3
    paginate_orphans = 1

    def dispatch(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) | Q(author__icontains=self.search_value))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # super(ArticleListView, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form
        if self.search_value:
            context["query"] = urlencode({"search": self.search_value})
            context["search_value"] = self.search_value
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'articles/article_create.html'
    form_class = ArticleForm

    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={"pk": self.object.pk})

    #def dispatch(self, request, *args, **kwargs):
    #    if request.user.is_authenticated:
    #        return super().dispatch(request, *args, **kwargs)
    #    else:
    #       return redirect("accounts:login")

    #def form_valid(self, form):
    #    article = form.save()
    #    return redirect("webapp:article_detail", pk=article.pk)  # super().form_valid(form)


class ArticleView(DetailView):
    template_name = 'articles/article_view.html'
    model = Article
    context_object_name = "article"

    def get_context_object_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = self.object.comments.order_by("created_at")  # self.get_object()
        return context


class ArticleUpdateView(UpdateView):
    model = Article
    template_name = "articles/article_update.html"
    form_class = ArticleForm


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = "articles/delete_article.html"
    success_url = reverse_lazy("webapp:articles")

source/webapp/views/comments.py
from django.views.generic import CreateView, UpdateView, DeleteView
from webapp.models import Comment, Article
from webapp.forms import CommentForm
from django.urls import reverse
from django.shortcuts import get_object_or_404, redirect


class CommentsCreateView(CreateView):
    model = Comment
    template_name = "comments/comment_create.html"
    form_class = CommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        form.instance.article = article
        return super().form_valid(form)


    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={"pk": self.object.article.pk})


class CommentUpdateView(UpdateView):
    model = Comment
    template_name = "comments/comment_update.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse('webapp:article_detail', kwargs={"pk": self.object.article.pk})

class CommentDeleteView(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect("webapp:article_detail", pk=self.object.article.pk)

source/webapp/templates/articles/article_create.html
{% extends "base.html" %}
{% block title %}Create Article{% endblock %}
{% block content %}

    <div class="container">
        <h1>Create Article</h1>
        <form action="{% url 'webapp:create_article' %}" method="post">
            {% include "partial/article_form.html" with button="Save" %}
        </form>
    </div>
    
{% endblock %}

source/webapp/templates/articles/article_update.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-5">
    <h1>Edit Article "{{ article.title }}"</h1>
    <form action="" method="post">
    {% include "partial/article_form.html" with button="Edit" %}
</form>
</div>
    
{% endblock %}

source/webapp/templates/articles/article_view.html
{% extends "base.html" %}
{% block title %}{{ article.title }}{% endblock %}
{% block menu %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'webapp:update_article' article.id %}">Edit article</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'webapp:comment_add' article.id %}">Add comment</a>
    </li>

{% endblock %}
{% block content %}
    
<div class="container">
        <h1 class="my-5">Article</h1>
        <div class="card my-5">
            <h3 class="card-header">{{ article.title }}</h3>
            <div class="card-body">
                <h5 class="card-title">Author: {{ article.author }}</h5>
                <p class="card-text">{{ article.content }}</p>
                    {% if article.tags.exists %}
                        <p class="card-text">
                            Tags:
                            {% for tag in article.tags.all %}
                                {{ tag.name}}
                                {% if forloop.last %}.
                                {% else %},
                                {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}
                <a href="/" class="btn btn-primary">На главную</a>
            </div>
        </div>
        <h3 class="#">Comments:</h3>
        {% for comment in article.comments.all %}
            <div class="row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Author: {{ comment.author }}</h5>
                            <p class="card-text">{{ comment.text }}</p>
                            <a href="{% url 'webapp:update_comment' comment.pk %}"><svg style="height: 20px; width: 20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160L0 416c0 53 43 96 96 96l256 0c53 0 96-43 96-96l0-96c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 96c0 17.7-14.3 32-32 32L96 448c-17.7 0-32-14.3-32-32l0-256c0-17.7 14.3-32 32-32l96 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L96 64z"/></svg></a>
                            <a href="{% url 'webapp:delete_comment' comment.pk %}" class="mx-3"><svg style="height: 20px; width: 20px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.7.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg></a>
                            
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="card-text">Comment section is empty.</p>
        {% endfor %}
    </div>

{% endblock %}

source/webapp/templates/articles/delete_article.html
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
<h1>Удаление</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" style="width: 100px" class="btn btn-danger">Delete</button>
        <a href="{% url 'articles'%}" style="width: 100px" class="btn btn-warning mx-2">Cancel</a>
    </form>
    

</div>
    
{% endblock %}

source/webapp/templates/articles/index.html
{% extends "base.html" %}
{% block title %}Статьи{% endblock %}
{% block menu %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'webapp:create_article' %}">New article</a>
    </li>




{% endblock %}

{% block content %}

    <h1>Articles</h1>
    <div class="my-5">
        {% include 'partial/search.html' with form=search_form %}
    </div>

    <div class="my-5">
        {% include "partial/pagination.html" %}
    </div>

    <div class="container my-5">


        <div class="row row-cols-1 row-cols-md-3 g-4" style="margin-bottom: 50px">
            {% for article in articles %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ article.title }}</h5>
                            <p class="card-text">Автор: {{ article.author }}</p>
                            <a href="{% url 'webapp:update_article' article.pk %}">
                                <svg style="height: 20px; width: 20px" xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 512 512">
                                    <!--!Font Awesome Free 6.7.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                                    <path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160L0 416c0 53 43 96 96 96l256 0c53 0 96-43 96-96l0-96c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 96c0 17.7-14.3 32-32 32L96 448c-17.7 0-32-14.3-32-32l0-256c0-17.7 14.3-32 32-32l96 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L96 64z"/>
                                </svg>
                            </a>
                            <a href="{% url 'webapp:delete_article' article.pk %}" class="mx-3">
                                <svg style="height: 20px; width: 20px" xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 448 512">
                                    <!--!Font Awesome Free 6.7.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                                    <path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                                </svg>
                            </a>
                            <a href="{% url 'webapp:article_detail' article.pk %}"
                               style="margin-left: 170px">Подробнее</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}